app/user/__init__.py
# app/user/__init__.py

from flask import Blueprint

user = Blueprint('user', __name__, url_prefix='/user')

from . import views

app/user/views.py
# app/user/views.py
import os

from flask_login import current_user, login_required

from . import user
from flask import render_template, abort, request, url_for, send_from_directory, redirect, flash, current_app

from ..extensions import avatars, db
from ..models import User


@user.route('/<username>/')
def user_profile(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    return render_template('user/user-profile.html', user=user)


@user.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory('static/avatars', filename)


@user.route('/change-avatar/', methods=['GET', 'POST'])
@login_required
def upload():
    if request.method == 'POST':
        f = request.files.get('file')
        raw_filename = avatars.save_avatar(f)
        u = current_user._get_current_object()
        u.raw_avatar = raw_filename
        db.session.add(u)
        db.session.commit()
        return redirect(url_for('user.crop'))
    return render_template('user/change-avatar-upload.html')


@user.route('/change-avatar/crop/', methods=['GET', 'POST'])
@login_required
def crop():
    if request.method == 'POST':
        x = request.form.get('x')
        y = request.form.get('y')
        w = request.form.get('w')
        h = request.form.get('h')
        filenames = avatars.crop_avatar(current_user.raw_avatar, x, y, w, h)
        u = current_user._get_current_object()
        u.avatar_s = filenames[0]
        u.avatar_m = filenames[1]
        u.avatar_l = filenames[2]
        db.session.add(u)
        db.session.commit()
        flash('更改头像成功', 'success')
        return redirect(url_for('user.user_profile', username=u.username))
    return render_template('user/change-avatar-crop.html')


@user.route('/change-avatar/default/')
@login_required
def default_avatar():
    u = current_user._get_current_object()
    u.avatar_l = '%s_l.png' % u.username
    u.avatar_m = '%s_m.png' % u.username
    u.avatar_s = '%s_s.png' % u.username
    db.session.add(u)
    db.session.commit()
    flash('头像已恢复为默认头像', 'success')
    return redirect(url_for('user.user_profile', username=u.username))


@user.route('/change-bg/', methods=['GET', 'POST'])
def upload_background():
    if request.method == 'POST' and 'file' in request.files:
        file = request.files['file']
        ext = file.filename.rsplit('.', 1)[1].lower()
        filename = '%s_bg.%s' % (current_user.username, ext)
        file.save(os.path.join(current_app.config['BACKGROUNDS_SAVE_PATH'], filename))
        return redirect(url_for('uploaded_file', filename=filename))

app/templates/user/change-avatar-crop.html
<!--app/templates/user/change-avatar-crop.html-->
{% extends 'base.html' %}

{% block title %}更改头像 - AttributeError{% endblock %}

{% block content %}
    {{ avatars.jcrop_css() }}  <!--导入内置的jcrop css-->
    <div class="container">
        <h1>更改头像</h1>
        <hr>
        <div class="card">
            <div class="card-body container-fluid">
                {{ avatars.crop_box('user.get_avatar', current_user.raw_avatar) }}
                {{ avatars.preview_box('user.get_avatar', current_user.raw_avatar) }}
                <br>
                <form method="post">
                    <input type="hidden" id="x" name="x">
                    <input type="hidden" id="y" name="y">
                    <input type="hidden" id="w" name="w">
                    <input type="hidden" id="h" name="h">
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ avatars.jcrop_js() }}  <!--导入Flask-Avatars内置的jcrop js-->
    {{ avatars.init_jcrop() }}
{% endblock %}

app/templates/user/change-avatar-upload.html
<!--app/templates/user/change-avatar-upload.html-->
{% extends 'base.html' %}

{% block title %}上传头像 - AttributeError{% endblock %}

{% block content %}
    <div class="container">
        <h1>上传头像</h1>
        <button class="btn btn-outline-primary" data-toggle="modal" data-target="#confirm">
            恢复为默认头像
        </button>
        <hr>
        <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">你确定吗？</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        你确定要将头像恢复为默认头像吗？你之后还可以将其设置为自定义头像
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                        <a class="btn btn-primary" href="{{ url_for('user.default_avatar') }}">确定</a>
                    </div>
                </div>
            </div>
        </div>
        <form method="post" enctype="multipart/form-data">
            <div class="input-group">
                <input id='location' class="form-control" onclick="$('#file').click();">
                <label class="input-group-prepend">
                    <input type="button" value="上传头像" id="i-check" class="btn btn-primary rounded-right"
                           onclick="$('#file').click();">
                </label>
            </div>
            <input type="file" name="file" id='file' accept="image/png image/jpg image/jpeg image/gif"
                   onchange="$('#location').val(getFileName(this.value));" style="display: none">
            <button class="btn btn-success" type="submit">上传</button>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        function getFileName(path) {
            var pos1 = path.lastIndexOf('/');
            var pos2 = path.lastIndexOf('\\');
            var pos = Math.max(pos1, pos2);
            if (pos < 0)
                return path;
            else
                return path.substring(pos + 1);
        }
    </script>
{% endblock %}

app/templates/user/user-profile.html
<!--app/templates/user/user-profile.html-->
{% extends 'base.html' %}

{% block title %}{{ user.username }} - AttributeError{% endblock %}

{% block content %}
    <div class="container">
        <div class="row container">
            <div class="col col-3 text-center">
                <img class="rounded-circle img-fluid" src="{{ url_for('static', filename='avatars/%s' % user.avatar_l) }}" onerror="this.src='{{ avatars.default(size='l') }}';">
                {% if user == current_user %} {# 判断用户是不是当前用户 #}
                    <br><a style="margin-top: 10px" href="{{ url_for('user.upload') }}" class="btn btn-primary">更改头像 <span class="fa fa-edit"></span></a>
                {% endif %}
            </div>
            <div class="col col-9">
                <h1>{{ user.username }}{% if user.real_name %} <small><small><small class="text-muted font-weight-light"> {{ user.real_name }}</small></small></small>{% endif %}{% if user.gender == 'male' %} <span class="fa fa-mars" style="font-size: 50%; color: #007bff"></span>{% elif user.gender == 'female' %} <span class="fa fa-venus" style="font-size: 50%; color: #e83e8c"></span>{% endif %}</h1>
                {% if user.site %}<p><a href="//{{ user.site }}" target="_blank">{{ user.site }} <small class="fa fa-external-link text-secondary"></small></a></p>{% endif %}
                {% if user.about %}<span class="fa fa-quote-left"></span> <blockquote class="blockquote font-italic font-weight-light">{{ user.about }}</blockquote>{% endif %}
                注册于{{ moment(user.member_since).fromNow() }}
            </div>
        </div>
        <hr>
    </div>
{% endblock %}